name: Build and Push to ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: ecr_login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 480611177231.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t aws_deploye .

      - name: Tag Docker image
        run: docker tag aws_deploye:latest 480611177231.dkr.ecr.us-east-1.amazonaws.com/aws_deploye:latest

      - name: Push Docker image to ECR
        run: docker push 480611177231.dkr.ecr.us-east-1.amazonaws.com/aws_deploye:latest

      - name: Deploy to ECS
        run: |
            aws ecs update-service \
              --cluster githubactions  \
              --service sprindemoservice \
              --force-new-deployment \
              --region us-east-1
